#!/usr/bin/env bash
# Render deploy/Caddyfile from instance.env.
# VPS: main site (ArozOS + Joshu API) + optional Hermes dashboard on its own hostname at :9119 root.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-/etc/joshu/instance.env}"
OUT="${CADDYFILE_OUT:-${ROOT_DIR}/Caddyfile}"

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

CUSTOMER_DOMAIN="${CUSTOMER_DOMAIN:?CUSTOMER_DOMAIN is required to render Caddyfile}"

direct=false
if [[ "${JOSHU_HERMES_DASHBOARD_DIRECT:-true}" =~ ^(1|true|yes)$ ]]; then
  direct=true
fi

HERMES_DASHBOARD_DOMAIN="${HERMES_DASHBOARD_DOMAIN:-hermes-admin.${CUSTOMER_DOMAIN}}"

cat >"${OUT}" <<EOF
# Generated by deploy/scripts/render-caddyfile.sh — do not edit by hand
${CUSTOMER_DOMAIN} {
	encode gzip
	reverse_proxy /joshu/* 127.0.0.1:8788
	reverse_proxy /voice/* 127.0.0.1:8791
	reverse_proxy /voice-rt/* 127.0.0.1:8792
	reverse_proxy 127.0.0.1:8787
}
EOF

if [[ "${direct}" != true ]]; then
  # Legacy subpath mode: kanban plugin may hit /api/plugins/kanban at site root.
  cat >>"${OUT}" <<'EOF'

	handle /api/plugins/kanban* {
		uri replace /api /joshu/hermes-admin/api
		reverse_proxy 127.0.0.1:8788
	}
EOF
fi

if [[ "${direct}" == true && -n "${HERMES_DASHBOARD_DOMAIN}" ]]; then
  AUTH_USER="${JOSHU_HERMES_DASHBOARD_USER:-admin}"
  BCRYPT=""
  if [[ -n "${JOSHU_HERMES_DASHBOARD_PASSWORD:-}" ]]; then
    if command -v docker >/dev/null 2>&1; then
      BCRYPT="$(docker run --rm caddy:2-alpine caddy hash-password --plaintext "${JOSHU_HERMES_DASHBOARD_PASSWORD}" 2>/dev/null || true)"
    fi
    if [[ -z "${BCRYPT}" ]] && command -v caddy >/dev/null 2>&1; then
      BCRYPT="$(caddy hash-password --plaintext "${JOSHU_HERMES_DASHBOARD_PASSWORD}" 2>/dev/null || true)"
    fi
    if [[ -z "${BCRYPT}" ]]; then
      echo "[render-caddyfile] WARN: could not bcrypt JOSHU_HERMES_DASHBOARD_PASSWORD; Hermes admin vhost will rely on session token only" >&2
    fi
  fi

  {
    echo ""
    echo "# Hermes dashboard — served at site root (upstream :9119); no Joshu path-prefix proxy"
    echo "${HERMES_DASHBOARD_DOMAIN} {"
    echo "	encode gzip"
    if [[ -n "${BCRYPT}" ]]; then
      echo "	basicauth {"
      echo "		${AUTH_USER} ${BCRYPT}"
      echo "	}"
    fi
    echo "	# Hermes binds 127.0.0.1 and rejects non-loopback Host (GHSA-ppp5-vxwm-4cf7)"
    echo "	reverse_proxy 127.0.0.1:${HERMES_DASHBOARD_PORT:-9119} {"
    echo "		header_up Host 127.0.0.1:${HERMES_DASHBOARD_PORT:-9119}"
    echo "	}"
    echo "}"
  } >>"${OUT}"
fi

echo "[render-caddyfile] wrote ${OUT} (direct=${direct} hermes=${HERMES_DASHBOARD_DOMAIN:-off})"
