#!/bin/sh
# Render a Caddyfile from instance.env.
#
# Runs in two places (POSIX sh so it also works inside caddy:2-alpine):
#   - on the host for debugging / bootstrap (writes to deploy/Caddyfile), and
#   - inside the caddy container via deploy/scripts/caddy-entrypoint.sh, which
#     regenerates /etc/caddy/Caddyfile on every start.
# Regenerating on start makes the edge config self-healing: a git reset/pull/sync
# on the clone can no longer leave Caddy serving a stale/empty config.
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${1:-/etc/joshu/instance.env}"
OUT="${CADDYFILE_OUT:-${ROOT_DIR}/Caddyfile}"

if [ -f "${ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi

is_true() {
  case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
    1 | true | yes) return 0 ;;
    *) return 1 ;;
  esac
}

mkdir -p "$(dirname "${OUT}")"

# Self-host without a public domain: emit a plain-HTTP :80 site so the entrypoint
# still produces a valid config instead of failing hard.
if [ -z "${CUSTOMER_DOMAIN:-}" ]; then
  echo "[render-caddyfile] WARN: CUSTOMER_DOMAIN unset — rendering HTTP-only :80 site" >&2
  cat >"${OUT}" <<'EOF'
# Generated by deploy/scripts/render-caddyfile.sh — do not edit by hand (CUSTOMER_DOMAIN unset)
:80 {
	encode gzip
	reverse_proxy /joshu/* 127.0.0.1:8788 {
		flush_interval -1
		transport http {
			read_timeout 1h
			write_timeout 1h
		}
	}
	reverse_proxy /voice/* 127.0.0.1:8791
	reverse_proxy /voice-rt/* 127.0.0.1:8792
	reverse_proxy 127.0.0.1:8787
}
EOF
  echo "[render-caddyfile] wrote ${OUT} (http-only)"
  exit 0
fi

direct=true
is_true "${JOSHU_HERMES_DASHBOARD_DIRECT:-true}" || direct=false

HERMES_DASHBOARD_DOMAIN="${HERMES_DASHBOARD_DOMAIN:-hermes-admin.${CUSTOMER_DOMAIN}}"

CADDY_EMAIL_BLOCK=""
if [ -n "${ACME_EMAIL:-}" ]; then
  CADDY_EMAIL_BLOCK="{
	email ${ACME_EMAIL}
}
"
fi

cat >"${OUT}" <<EOF
# Generated by deploy/scripts/render-caddyfile.sh — do not edit by hand
${CADDY_EMAIL_BLOCK}${CUSTOMER_DOMAIN} {
	encode gzip
	reverse_proxy /joshu/* 127.0.0.1:8788 {
		flush_interval -1
		transport http {
			read_timeout 1h
			write_timeout 1h
		}
	}
	reverse_proxy /voice/* 127.0.0.1:8791
	reverse_proxy /voice-rt/* 127.0.0.1:8792
	reverse_proxy 127.0.0.1:8787
}
EOF

if [ "${direct}" != true ]; then
  # Legacy subpath mode: kanban plugin may hit /api/plugins/kanban at site root.
  cat >>"${OUT}" <<'EOF'

	handle /api/plugins/kanban* {
		uri replace /api /joshu/hermes-admin/api
		reverse_proxy 127.0.0.1:8788
	}
EOF
fi

if [ "${direct}" = true ] && [ -n "${HERMES_DASHBOARD_DOMAIN}" ]; then
  AUTH_USER="${JOSHU_HERMES_DASHBOARD_USER:-admin}"
  BCRYPT=""
  if [ -z "${JOSHU_HERMES_DASHBOARD_PASSWORD:-}" ]; then
    echo "[render-caddyfile] SKIP hermes-admin vhost: JOSHU_HERMES_DASHBOARD_PASSWORD unset (unauthenticated dashboard can add stdio MCPs)" >&2
  else
    # Prefer the in-image caddy binary (works inside the container); fall back to
    # docker on hosts that lack a caddy binary.
    if command -v caddy >/dev/null 2>&1; then
      BCRYPT="$(caddy hash-password --plaintext "${JOSHU_HERMES_DASHBOARD_PASSWORD}" 2>/dev/null || true)"
    fi
    if [ -z "${BCRYPT}" ] && command -v docker >/dev/null 2>&1; then
      BCRYPT="$(docker run --rm caddy:2-alpine caddy hash-password --plaintext "${JOSHU_HERMES_DASHBOARD_PASSWORD}" 2>/dev/null || true)"
    fi
    if [ -z "${BCRYPT}" ]; then
      echo "[render-caddyfile] SKIP hermes-admin vhost: could not bcrypt JOSHU_HERMES_DASHBOARD_PASSWORD" >&2
    else
      {
        echo ""
        echo "# Hermes dashboard — served at site root (upstream :9119); no Joshu path-prefix proxy"
        echo "${HERMES_DASHBOARD_DOMAIN} {"
        echo "	encode gzip"
        echo "	basicauth {"
        echo "		${AUTH_USER} ${BCRYPT}"
        echo "	}"
        echo "	# Hermes binds 127.0.0.1 and rejects non-loopback Host (GHSA-ppp5-vxwm-4cf7)"
        echo "	reverse_proxy 127.0.0.1:${HERMES_DASHBOARD_PORT:-9119} {"
        echo "		header_up Host 127.0.0.1:${HERMES_DASHBOARD_PORT:-9119}"
        echo "	}"
        echo "}"
      } >>"${OUT}"
    fi
  fi
fi

echo "[render-caddyfile] wrote ${OUT} (direct=${direct} hermes=${HERMES_DASHBOARD_DOMAIN:-off})"
