#!/usr/bin/env bash
# Twilio phone voice — local dev helper (single ngrok + proxy).
#
# Typical flow:
#   Terminal 1: npm run dev:arozos
#   Terminal 2: npm run voice-realtime:dev   # if JOSHU_VOICE_MODE=realtime_s2s
#   Terminal 3: npm run twilio-local:proxy
#   Terminal 4: npm run twilio-local:ngrok
#   Then: npm run twilio-local:urls  (paste into .env + Twilio console)
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib/twilio-local-env.sh
source "${ROOT_DIR}/scripts/lib/twilio-local-env.sh"

twilio_local_load_env "${ROOT_DIR}"

cmd="${1:-help}"
shift || true

usage() {
  cat <<'EOF'
Twilio local testing (one ngrok tunnel via scripts/twilio-local-proxy.mjs)

Commands:
  help          Show this message
  proxy         Start reverse proxy on :8790 (joshu + voice-rt)
  ngrok         Start ngrok http 8790 (requires ngrok CLI)
  urls          Print TWILIO_* URLs from ngrok API (run ngrok first)
  env           Append/update .env.twilio.local snippet (from ngrok urls)
  check         Preflight: secrets, local health, tunnel health

Prerequisites (other terminals):
  npm run dev:arozos
  JOSHU_VOICE_MODE=realtime_s2s  ->  npm run voice-realtime:dev
  JOSHU_VOICE_MODE=realtime_s2s  ->  npm run voice-realtime:dev (autostarted by dev:arozos)

Env:
  JOSHU_VOICE_MODE=legacy | realtime | realtime_s2s
  TWILIO_LOCAL_PROXY_PORT=8790
  TWILIO_AUTH_TOKEN, TWILIO_MEDIA_STREAM_SECRET

Docs: docs/vps-sandbox/phone-voice-local-test.md
      docs/vps-sandbox/voice-realtime.md
EOF
}

cmd_proxy() {
  echo "[twilio-local] starting proxy on port $(twilio_local_proxy_port)"
  exec node "${ROOT_DIR}/scripts/twilio-local-proxy.mjs"
}

cmd_ngrok() {
  if ! command -v ngrok >/dev/null 2>&1; then
    echo "[twilio-local] install ngrok: https://ngrok.com/download" >&2
    exit 1
  fi
  local port
  port="$(twilio_local_proxy_port)"
  echo "[twilio-local] ngrok http ${port}"
  echo "[twilio-local] Start the proxy first in another terminal: npm run twilio-local:proxy"
  echo "[twilio-local] Do NOT use 'ngrok http 8788' for realtime_s2s — /voice-rt is on :8792 via proxy only."
  exec ngrok http "${port}"
}

ngrok_public_url() {
  if ! command -v curl >/dev/null 2>&1; then
    return 1
  fi
  curl -fsS "http://127.0.0.1:4040/api/tunnels" 2>/dev/null \
    | python3 -c "
import json, sys
data = json.load(sys.stdin)
for t in data.get('tunnels', []):
    u = t.get('public_url', '')
    if u.startswith('https://'):
        print(u)
        break
" 2>/dev/null || true
}

cmd_urls() {
  twilio_local_ensure_secret || exit 1
  local origin
  origin="$(ngrok_public_url)"
  if [[ -z "${origin}" ]]; then
    echo "[twilio-local] no ngrok https tunnel on :4040 — start: npm run twilio-local:ngrok" >&2
    exit 1
  fi

  local webhook wss mode
  mode="$(twilio_local_voice_mode)"
  webhook="$(twilio_local_webhook_url "${origin}")"
  wss="$(twilio_local_media_wss_url "${origin}" "${TWILIO_MEDIA_STREAM_SECRET}")"

  echo ""
  echo "=== Twilio local URLs (mode=${mode}) ==="
  echo ""
  echo "TWILIO_VOICE_WEBHOOK_URL=${webhook}"
  echo "TWILIO_MEDIA_STREAM_WSS_URL=${wss}"
  echo ""
  echo "Twilio Console → Phone number → Voice webhook (POST):"
  echo "  ${webhook}"
  echo ""
  echo "Health:"
  echo "  curl -H 'ngrok-skip-browser-warning: 1' ${origin}$(twilio_local_base_path)/api/twilio/health"
  case "${mode}" in
    realtime_s2s) echo "  curl ${origin}/voice-rt/health" ;;
    realtime) echo "  curl ${origin}/voice/health" ;;
  esac
  echo ""
}

cmd_env() {
  twilio_local_ensure_secret || exit 1
  local origin
  origin="$(ngrok_public_url)"
  if [[ -z "${origin}" ]]; then
    echo "[twilio-local] no ngrok tunnel — start ngrok first" >&2
    exit 1
  fi

  local snippet_file="${ROOT_DIR}/.env.twilio.local"
  local webhook wss
  webhook="$(twilio_local_webhook_url "${origin}")"
  wss="$(twilio_local_media_wss_url "${origin}" "${TWILIO_MEDIA_STREAM_SECRET}")"

  cat >"${snippet_file}" <<EOF
# Generated by: npm run twilio-local:env
# Merge into .env or: set -a && source .env.twilio.local && set +a

TWILIO_VOICE_WEBHOOK_URL=${webhook}
TWILIO_MEDIA_STREAM_WSS_URL=${wss}
TWILIO_MEDIA_STREAM_SECRET=${TWILIO_MEDIA_STREAM_SECRET}
PUBLIC_BASE_PATH=$(twilio_local_base_path)
JOSHU_HTTP_BASE_URL=http://127.0.0.1:8788$(twilio_local_base_path)
EOF

  echo "[twilio-local] wrote ${snippet_file}"
  echo "[twilio-local] restart Joshu after sourcing so TwiML picks up new WSS URL"
  cat "${snippet_file}"
}

cmd_check() {
  twilio_local_ensure_secret || true
  export PHONE_VOICE_PUBLIC_HOST
  PHONE_VOICE_PUBLIC_HOST="$(ngrok_public_url)"
  if [[ -n "${PHONE_VOICE_PUBLIC_HOST}" ]]; then
    echo "[twilio-local] tunnel origin: ${PHONE_VOICE_PUBLIC_HOST}"
  else
    echo "[twilio-local] no ngrok tunnel (optional for local-only checks)"
  fi
  node "${ROOT_DIR}/scripts/twilio-local-check.mjs"
}

case "${cmd}" in
  help|-h|--help) usage ;;
  proxy) cmd_proxy ;;
  ngrok) cmd_ngrok ;;
  urls) cmd_urls ;;
  env) cmd_env ;;
  check) cmd_check ;;
  *)
    echo "Unknown command: ${cmd}" >&2
    usage
    exit 1
    ;;
esac
